name: Github Pages
on:
  push:
    branches:
      - main
  schedule:
    # Run this script every 15 minutes
    - cron:  '*/15 * * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      # Set up any tools and build steps here
      # This example uses a Node.js toolchain to build a site
      - name: Install and Run Zola
        run: |
          npm install -g pnpm
          pnpm intall
          pnpm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: output # The folder the action should deploy.
